ci: run federated ocis

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -63,18 +63,30 @@ jobs:
     strategy:
       matrix:
         suites:
-          - admin-settings
-          - app-provider
-          - app-store
-          - file-action
-          - navigation
-          - ocm
-          - oidc
-          - runtime
-          - search
-          - shares
-          - smoke
-          - user-settings
+          - name: admin-settings
+            federated: false
+          - name: app-provider
+            federated: false
+          - name: app-store
+            federated: false
+          - name: file-action
+            federated: false
+          - name: navigation
+            federated: false
+          - name: ocm
+            federated: true
+          - name: oidc
+            federated: false
+          - name: runtime
+            federated: false
+          - name: search
+            federated: false
+          - name: shares
+            federated: false
+          - name: smoke
+            federated: false
+          - name: user-settings
+            federated: false
     env:
       BASE_URL_OCIS: localhost:9200
       HEADLESS: true
@@ -84,6 +96,7 @@ jobs:
       FAILD_ON_UNCAUGHT_CONSOLE_ERR: trye
       SKIP_A11Y_TESTS: true
       TEST_TYPE: playwright
+      FEDERATED_BASE_URL_OCIS: localhost:10200
     steps:
       - name: Checkout code
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
@@ -94,7 +107,7 @@ jobs:
           name: web-dist
           path: dist
 
-      - name: Run oCIS
+      - name: Run oCIS service
         run: |
           docker run -d \
             --name ocis \
@@ -155,6 +168,69 @@ jobs:
           docker inspect ocis
           exit 1
 
+      - name: Run federated oCIS service
+        if: matrix.suites.federated == true
+        run: |
+          docker run -d \
+            --name ocis-federated \
+            -p 10200:10200 \
+            -v ${{ github.workspace }}:/workspace \
+            -e IDM_ADMIN_PASSWORD=admin \
+            -e OCIS_INSECURE=true \
+            -e OCIS_LOG_LEVEL=error \
+            -e OCIS_JWT_SECRET=some-ocis-jwt-secret \
+            -e LDAP_GROUP_SUBSCRIPTION_FILTER_TYPE=any \
+            -e LDAP_USER_SUBSCRIPTION_FILTER_TYPE=any \
+            -e PROXY_ENABLE_BASIC_AUTH=true \
+            -e WEB_ASSET_CORE_PATH=/workspace/dist \
+            -e FRONTEND_SEARCH_MIN_LENGTH=2 \
+            -e OCIS_PASSWORD_POLICY_BANNED_PASSWORDS_LIST=/workspace/tests/drone/banned-passwords.txt \
+            -e PROXY_CSP_CONFIG_FILE_LOCATION=/workspace/tests/drone/csp.yaml \
+            -e GRAPH_AVAILABLE_ROLES=b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6,63e64e19-8d43-42ec-a738-2b6af2610efa \
+            -e FRONTEND_CONFIGURABLE_NOTIFICATIONS=true \
+            -e OCIS_URL=https://localhost:10200 \
+            -e WEB_UI_CONFIG_FILE=/workspace/tests/drone/config-ocis.json \
+            -e OCIS_TRANSFER_SECRET=some-ocis-transfer-secret \
+            -e OCIS_LOG_PRETTY=true \
+            -e OCIS_LOG_COLOR=true \
+            -e OCIS_ADMIN_USER_ID=some-admin-user-id-0000-000000000000 \
+            -e OCIS_SYSTEM_USER_ID=some-system-user-id-000-000000000000 \
+            -e OCIS_SYSTEM_USER_API_KEY=some-system-user-machine-auth-api-key \
+            -e OCIS_MACHINE_AUTH_API_KEY=some-ocis-machine-auth-api-key \
+            -e COLLABORATION_WOPIAPP_SECRET=some-wopi-secret \
+            -e IDM_SVC_PASSWORD=some-ldap-idm-password \
+            -e GRAPH_LDAP_BIND_PASSWORD=some-ldap-idm-password \
+            -e IDM_REVASVC_PASSWORD=some-ldap-reva-password \
+            -e GROUPS_LDAP_BIND_PASSWORD=some-ldap-reva-password \
+            -e USERS_LDAP_BIND_PASSWORD=some-ldap-reva-password \
+            -e AUTH_BASIC_LDAP_BIND_PASSWORD=some-ldap-reva-password \
+            -e IDM_IDPSVC_PASSWORD=some-ldap-idp-password \
+            -e IDP_LDAP_BIND_PASSWORD=some-ldap-idp-password \
+            -e GATEWAY_STORAGE_USERS_MOUNT_ID=storage-users-1 \
+            -e STORAGE_USERS_MOUNT_ID=storage-users-1 \
+            -e GRAPH_APPLICATION_ID=application-1 \
+            -e OCIS_SERVICE_ACCOUNT_ID=service-account-id \
+            -e OCIS_SERVICE_ACCOUNT_SECRET=service-account-secret \
+            owncloud/ocis-rolling:latest
+
+      - name: Wait for federated oCIS service
+        if: matrix.suites.federated == true
+        run: |
+          echo "Waiting for federated oCIS"
+          # 150s timeout
+          for i in {1..30}; do
+            if curl -kfsSL https://localhost:10200 > /dev/null; then
+              echo "federated oCIS is up ✅"
+              exit 0
+            fi
+            echo "Retrying in 5s..."
+            sleep 5
+          done
+          echo "❌ federated oCIS failed to start"
+          docker logs ocis-federated
+          docker inspect ocis-federated
+          exit 1
+
       - name: Setup pnpm
         uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
         with:
@@ -180,4 +256,4 @@ jobs:
         run: pnpm exec playwright install --with-deps chromium
 
       - name: Run E2E tests
-        run: cd ${{ github.workspace }}/tests/e2e && bash run-e2e.sh --type playwright --suites ${{ matrix.suites }}
+        run: cd ${{ github.workspace }}/tests/e2e && bash run-e2e.sh --type playwright --suites ${{ matrix.suites.name }}
